<a href="https://colab.research.google.com/github/jesse-venson/Cognitive/blob/main/cog_a4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#question 1
import numpy as np
arr=np.array([1,2,3,4,5])
arr_add = arr + 2
print("Array after adding 2 to all elements:", arr_add)
arr_mul= arr*3
print("after mul",arr_mul)
arr_div= arr/2
print("after div",arr_div)



Array after adding 2 to all elements: [3 4 5 6 7]
after mul [ 3  6  9 12 15]
after div [0.5 1.  1.5 2.  2.5]


In [3]:
#question 2a
import numpy as np
arr=np.array([1,2,3,6,4,5])
arr_reversed = arr[::-1]
print("arr_reversed is",arr_reversed)

arr_reversed is [5 4 6 3 2 1]


In [5]:
#question 2b
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique_values, counts = np.unique(x, return_counts=True)

most_frequent_value = unique_values[np.argmax(counts)]

indices = np.where(x == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices of most frequent value: {indices}")


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
unique_values, counts = np.unique(y, return_counts=True)

most_frequent_value = unique_values[np.argmax(counts)]

indices = np.where(y == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices of most frequent value: {indices}")


Most frequent value: 1
Indices of most frequent value: [0 5 7 8 9]
Most frequent value: 1
Indices of most frequent value: [0 1 2]


In [7]:
#question 3
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
threea=arr[0,1]
threeb=arr[2,0]
print("first row second col ",threea )
print("third row first col ",threeb)


first row second col  20
third row first col  70


In [10]:
#question 4
import numpy as np
venson=np.linspace(10,100,25)
print("array is :",venson)
print("dimension of array: ",venson.ndim)
print("shape of array: ",venson.shape)
print("shape of array: ",venson.size)
print("shape of array: ",venson.dtype)
print("shape of array: ",venson.nbytes)
transposed_array_reshape = venson.reshape((1, -1))
print("Transpose using reshape():", transposed_array_reshape)


array is : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimension of array:  1
shape of array:  (25,)
shape of array:  25
shape of array:  float64
shape of array:  200
Transpose using reshape(): [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [14]:
#question 5
import numpy as np
ucs420_venson=np.array([[10, 20, 30, 40],
                       [50, 60, 70, 80],
                       [90, 15, 20, 35]])
mean=np.mean(ucs420_venson)
median=np.median(ucs420_venson)
max=np.max(ucs420_venson)
min=np.min(ucs420_venson)
unique=np.unique(ucs420_venson)
print("unique is ",unique)
print("mean is ",mean)
print("median is ",median)
print("max is ",max)
print("min is ",min)

reshaped_ucs420_venson=ucs420_venson.reshape(4,3)
print("reshaped is ",reshaped_ucs420_venson)

resized_ucs420_venson=np.resize(ucs420_venson,(2,3))
print("resized is ",resized_ucs420_venson)

unique is  [10 15 20 30 35 40 50 60 70 80 90]
mean is  43.333333333333336
median is  37.5
max is  90
min is  10
reshaped is  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized is  [[10 20 30]
 [40 50 60]]
